migrateup:
	 migrate -path Storage/migrations -database "postgresql://user:user@localhost:5440/chat_db?sslmode=disable" --verbose up

migratedown:
	 migrate -path Storage/migrations -database "postgresql://user:user@localhost:5440/chat_db?sslmode=disable" --verbose down